//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:ab51af28-8c30-4bb1-ad0b-016d21565dc9
    public partial class AffirmPanel
    {
        
        public const string NAME = "AffirmPanel";
        
        [SerializeField()]
        public CommonButton RightCommonButton;
        
        [SerializeField()]
        public UnityEngine.UI.Text ContentMCommonText;
        
        [SerializeField()]
        public CommonButton CrossCommonButton;
        
        private AffirmPanelData mPrivateData = null;
        
        public AffirmPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new AffirmPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            RightCommonButton = null;
            ContentMCommonText = null;
            CrossCommonButton = null;
            mData = null;
        }
    }
}
