//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    public class AffirmPanelData : QFramework.UIPanelData
    {
        public string AffirmContent { get; set; }
        public Action AffirmCallBack { get; set; }
    }

    public partial class AffirmPanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as AffirmPanelData ?? new AffirmPanelData();
            // please add init code here
            ContentMCommonText.text = mData.AffirmContent;
            RightCommonButton.Init(() =>
            {
                StartClose(() =>
                {
                    mData.AffirmCallBack?.Invoke();
                });
            });
            CrossCommonButton.Init(() =>
            {
                StartClose();
            });
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.TranslucentBlack));
            SendMsg(new AddCanvasGroupFadeQMsg(transform, true, null));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }

        private void StartClose(Action endCallback = null)
        {
            SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () =>
            {
                endCallback?.Invoke();
                CloseSelf();
            }));
        }
    }
}