//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:cf2716b6-2965-4136-9df2-1afb14bc42c8
    public partial class DialoguePanel
    {
        
        public const string NAME = "DialoguePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image HeadImage;
        
        [SerializeField()]
        public UnityEngine.UI.Text ContentText;
        
        [SerializeField()]
        public UnityEngine.UI.Button SkipButton;
        
        [SerializeField()]
        public UnityEngine.UI.Text NameText;
        
        [SerializeField()]
        public CommonButton GoOnButton;
        
        private DialoguePanelData mPrivateData = null;
        
        public DialoguePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new DialoguePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            HeadImage = null;
            ContentText = null;
            SkipButton = null;
            NameText = null;
            GoOnButton = null;
            mData = null;
        }
    }
}
