//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:0c66ebdc-be74-42b6-92e6-1ab83fc61378
    public partial class EndPanel
    {
        
        public const string NAME = "EndPanel";
        
        [SerializeField()]
        public CommonButton BackCommonButton;
        
        private EndPanelData mPrivateData = null;
        
        public EndPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new EndPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BackCommonButton = null;
            mData = null;
        }
    }
}
