//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:97e5a1e7-5e7d-488c-91e6-06f6bd57798e
    public partial class GameWinPanel
    {
        
        public const string NAME = "GameWinPanel";
        
        [SerializeField()]
        public CommonButton RightCommonButton;
        [SerializeField()]
        public CommonButton BackCommonButton;
        
        private GameWinPanelData mPrivateData = null;
        
        public GameWinPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GameWinPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            RightCommonButton = null;
            BackCommonButton = null;
            mData = null;
        }
    }
}
