//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;

    public class GameWinPanelData : QFramework.UIPanelData
    {
        public bool IsArriveMaxLevelNum { get; set; }
        public  int NextLevelNum { get; set; }
    }

    public partial class GameWinPanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as GameWinPanelData ?? new GameWinPanelData();
            // please add init code here
            BackCommonButton.Init(() =>
            {
                SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () =>
                {
                    CloseSelf();
                    SendEvent(LevelEvent.LoadLevelSelectScene);
                }));
            });
            
            RightCommonButton.Init(() =>
            {
                SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () =>
                {
                    CloseSelf();
                    if (mData.IsArriveMaxLevelNum)
                    {
                        SendEvent(LevelEvent.LoadEndScene);
                    }
                    else
                    {
                        SendMsg(new LevelQMsg(mData.NextLevelNum));
                    }
                }));
            });
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.TranslucentBlack));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}