//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:4e7dc826-58ff-44bf-80b7-e86f522205ef
    public partial class LogoPanel
    {
        
        public const string NAME = "LogoPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image LogoImage;
        
        private LogoPanelData mPrivateData = null;
        
        public LogoPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new LogoPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            LogoImage = null;
            mData = null;
        }
    }
}
