//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;

    public class LogoPanelData : QFramework.UIPanelData
    {
    }

    public partial class LogoPanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as LogoPanelData ?? new LogoPanelData();
            // please add init code here
            MenuManager.Instance.LogoAnimation(LogoImage.transform, () => { SendEvent(LevelEvent.LoadMainScene); });
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.PureBlack));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}