//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;

    public class PausePanelData : QFramework.UIPanelData
    {
        public Action EndCallback { get; set; }
    }

    public partial class PausePanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PausePanelData ?? new PausePanelData();
            // please add init code here
            CrossCommonButton.Init(() =>
            {
                SendEvent(GameEvent.UnPauseGame);
                SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () => { CloseSelf(); }));
            });
            
            BackCrossCommonButton.Init(() =>
            {
                Time.timeScale = 1f;
                SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () =>
                {
                    CloseSelf();
                    SendEvent(LevelEvent.LoadLevelSelectScene);
                }));
            });
            
            SendMsg(new AddCanvasGroupFadeQMsg(transform, true, mData.EndCallback));
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.TranslucentBlack));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}