//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:8cc5ef5d-3bce-4ecb-8168-c0b198f39a22
    public partial class PausePanel
    {
        
        public const string NAME = "PausePanel";
        
        [SerializeField()]
        public CommonButton CrossCommonButton;
        [SerializeField()]
        public CommonButton BackCrossCommonButton;
        
        private PausePanelData mPrivateData = null;
        
        public PausePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PausePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            CrossCommonButton = null;
            BackCrossCommonButton = null;
            mData = null;
        }
    }
}
