//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:7bc1d21e-4ca7-4033-b124-9e7f4744a33a
    public partial class PurdahPanel
    {
        
        public const string NAME = "PurdahPanel";
        
        private PurdahPanelData mPrivateData = null;
        
        public PurdahPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PurdahPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
