//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:368862e8-2e54-42a1-8bb5-99ed96ae1995
    public partial class SelectLevelPanel
    {
        
        public const string NAME = "SelectLevelPanel";
        
        [SerializeField()]
        public Content Content;
        
        [SerializeField()]
        public CommonButton BackCommonButton;
        
        private SelectLevelPanelData mPrivateData = null;
        
        public SelectLevelPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SelectLevelPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Content = null;
            BackCommonButton = null;
            mData = null;
        }
    }
}
