//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;

    public class SelectLevelPanelData : QFramework.UIPanelData
    {
    }

    public partial class SelectLevelPanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as SelectLevelPanelData ?? new SelectLevelPanelData();
            // please add init code here
            BackCommonButton.Init(() => { SendEvent(LevelEvent.LoadMainScene); });
            Content.Init(MainManager.Instance, SaveManager.Instance);
            SendMsg(new VoiceMsgQMsg("BG2", (int)VoiceEvent.PlayMusic));
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.Normal));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}