//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;
    using UniRx;

    public class SetPanelData : QFramework.UIPanelData
    {
        public BoolReactiveProperty IsShake { get; set; }
        public BoolReactiveProperty MusicOn { get; set; }
        public BoolReactiveProperty SoundOn { get; set; }
    }

    public partial class SetPanel : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as SetPanelData ?? new SetPanelData();
            // please add init code here
            RightCommonButton.Init(() =>
            {
                SendMsg(new AddCanvasGroupFadeQMsg(transform, false, () =>
                {
                    CloseSelf();
                    SendEvent(SaveEvent.Save);
                }));
            });
            SendMsg(new SetPanelColorQMsg(this, PanelColorType.TranslucentBlack));
            SendMsg(new ButtJointToggleQMsg(ShakeCommonToggle, mData.IsShake));
            SendMsg(new ButtJointToggleQMsg(MusicCommonToggle, mData.MusicOn));
            SendMsg(new ButtJointToggleQMsg(SoundCommonToggle, mData.SoundOn));
            SendMsg(new AddCanvasGroupFadeQMsg(transform, true, null));
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}