//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallPalCatGames.QFrameworkExtension
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:d8fba178-7475-4835-9062-3925379cd9c5
    public partial class SetPanel
    {
        
        public const string NAME = "SetPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Toggle ShakeCommonToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle MusicCommonToggle;
        
        [SerializeField()]
        public UnityEngine.UI.Toggle SoundCommonToggle;
        
        [SerializeField()]
        public CommonButton RightCommonButton;
        
        private SetPanelData mPrivateData = null;
        
        public SetPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new SetPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ShakeCommonToggle = null;
            MusicCommonToggle = null;
            SoundCommonToggle = null;
            RightCommonButton = null;
            mData = null;
        }
    }
}
